server:
  port: 8085

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/customers_db
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false


#
#
#  spring.sql.init.mode=always
