apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-flux-demo
spec:
  description: |
    This pipeline clones a git repo and runs testcontainers tests.
  params:
    - name: app-subdirectory
      type: string
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: image-tag
      type: string
    - name: manifest-repo
      type: string
    - name: manifest-subdirectory
      type: string

  workspaces:
    - name: shared-data
    - name: docker-credentials

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
        - name: subdirectory
          value: $(params.app-subdirectory)

    - name: list-source
      runAfter: [ "fetch-source" ]
      taskRef:
        name: list-source
      workspaces:
        - name: source
          workspace: shared-data

    - name: run-tests
      runAfter: ["list-source"]
      taskRef:
        name: run-tests
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: repo-location
          value: $(params.app-subdirectory)

    - name: build-push
      runAfter: [ "run-tests" ]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-reference):$(params.image-tag)
        - name: CONTEXT
          value: $(params.app-subdirectory)

    - name: fetch-manifest
      runAfter: [ "build-push" ]
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.manifest-repo)
        - name: deleteExisting
          value: "true"
        - name: subdirectory
          value: $(params.manifest-subdirectory)

#    - name: update-manifest
#      runAfter: [ "fetch-manifest" ]
#      taskRef:
#        name: update-manifest
#      workspaces:
#        - name: source
#          workspace: shared-data
#      params:
#        - name: file-path
#          value: flux/deployment.yaml
#        - name: repo-location
#          value: $(params.manifest-subdirectory)
#
#        - name: new-tag
#          value: $(tasks.fetch-source.results.commit)