apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-flux-demo-run
spec:
  pipelineRef:
    name: tekton-flux-demo
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credential

  params:
    - name: repo-url
      value: git@github.com:mhussain78/tekton-flux-demo.git

    - name: app-subdirectory
      value: tekton-flux-app

    - name: manifest-repo
      value: git@github.com:mhussain78/tekton-flux-demo-manifest.git

    - name: manifest-subdirectory
      value: manifest

    - name: image-reference
      value: mhussain78/tekton-flux-demo

    - name: image-tag
      value: 0.0.5

    - name: git-username
      value: mhussain78

    - name: git-email
      value: inf.mhussain@googlemail.com

  serviceAccountName: git-service-account