apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest
spec:
  workspaces:
    - name: source
      description: The source workspace for the manifest repository
  steps:
    - name: modify-manifest-file
      image: alpine/git
      script: |
        git config --global --add safe.directory $(workspaces.source.path)/$(inputs.params.repo-location)
        cd $(workspaces.source.path)/$(inputs.params.repo-location)
        pwd
        
        cat $(inputs.params.file-path)
        
        # Modify the file using sed command
        ESCAPED_IMAGE_TAG=$(printf '%s\n' "$(inputs.params.new-tag)" | sed -e 's/[]\/$*.^[]/\\&/g');
        sed -i "s/image.*/image: $ESCAPED_IMAGE_TAG/g" $(inputs.params.file-path)
        cat $(inputs.params.file-path)

        # Configure Git
        git config --global user.email "inf.mhussain@googlemail.com"
        git config --global user.name "mhussain78"

        # Commit the changes
        git add $(inputs.params.file-path)
        git commit -m "feat: Update manifest file with new tag"
        
        # Check Git status
        git status
        
        # Push the changes
        git push origin HEAD:refs/heads/main